import { auth, onAuthStateChanged } from "../dashboard/auth.js";
import { attendanceRequest } from "../dashboard/attendance-api.js";

const $=id=>document.getElementById(id); let data=null; let reviewRequest=null;
onAuthStateChanged(auth,user=>user?load():window.location.replace("./index.html"));
$("refreshBtn").addEventListener("click",load); $("statusFilter").addEventListener("change",renderPeople); $("searchInput").addEventListener("input",renderPeople);
$("saveTimeBtn").addEventListener("click",async()=>{try{await attendanceRequest("updateEndWarningTime",{time:$("endWarningTime").value});message("通知時刻を保存しました。");await load();}catch(e){message(e.message,true)}});

async function load(){try{data=await attendanceRequest("getAdminDashboard");$("endWarningTime").value=data.settings.end_warning_time||"19:00";render();message("最新情報を表示しています。");}catch(e){message(e.message,true);if(e.code==="FORBIDDEN")setTimeout(()=>location.replace("./dashboard.html"),1200)}}
function render(){const people=data.people||[];const status=p=>p.record?.["状態"]||"未開始";const counts={all:people.length,not:people.filter(p=>status(p)==="未開始").length,running:people.filter(p=>["稼働中","開始遅延"].includes(status(p))).length,issues:(data.requests||[]).length};$("summary").innerHTML=card("本日の予定",counts.all)+card("未開始",counts.not)+card("稼働中",counts.running)+card("承認待ち",counts.issues);renderPeople();renderRequests()}
function renderPeople(){const filter=$("statusFilter").value;const q=$("searchInput").value.toLowerCase();const items=(data.people||[]).filter(p=>{const status=p.record?.["状態"]||"未開始";const hay=[p.schedule?.["氏名"],p.record?.["氏名"],p.schedule?.email,p.record?.email,p.schedule?.["稼働場所"],p.record?.["予定場所"]].join(" ").toLowerCase();return(!filter||status===filter)&&(!q||hay.includes(q))});$("peopleRows").innerHTML=items.length?items.map(p=>{const s=p.schedule||{};const r=p.record||{};const status=r["状態"]||"未開始";const loc=p.location;const location=data.preciseLocationAccess&&loc?.["緯度"]?`<a class="location-link" target="_blank" rel="noopener" href="https://www.google.com/maps?q=${encodeURIComponent(loc["緯度"]+","+loc["経度"])}">地図で確認</a>`:(r["位置取得状態"]||"未取得");return`<tr><td><strong>${e(s["氏名"]||r["氏名"]||"—")}</strong><br><small>${e(s.email||r.email||"")}</small></td><td>${e(t(s["予定開始"]))}–${e(t(s["予定終了"]))}</td><td>${e(s["稼働場所"]||r["予定場所"]||"予定外")}</td><td><span class="badge ${cls(status)}">${e(status)}</span></td><td>${e(t(r["実開始"]))}</td><td>${e(t(r["実終了"]))}</td><td>${location}</td></tr>`}).join(""):`<tr><td colspan="7">該当者はいません。</td></tr>`}
function renderRequests(){const items=data.requests||[];$("requestCount").textContent=`${items.length}件`;$("requestList").innerHTML=items.length?items.map(r=>`<div class="request-item"><div><strong>${e(r["申請者氏名"]||r["申請者メール"])}・${e(r["種別"])}</strong><span>${e(r["理由区分"])}：${e(r["理由詳細"])}</span></div><button data-id="${e(r.request_id)}">確認</button></div>`).join(""):`<p>承認待ちの申請はありません。</p>`;document.querySelectorAll("[data-id]").forEach(b=>b.addEventListener("click",()=>openReview(b.dataset.id)))}
function openReview(id){reviewRequest=(data.requests||[]).find(r=>String(r.request_id)===id);if(!reviewRequest)return;$("reviewBody").innerHTML=`<p><strong>${e(reviewRequest["申請者氏名"]||reviewRequest["申請者メール"])}</strong></p><p>${e(reviewRequest["種別"])} / ${e(reviewRequest["理由区分"])}<br>${e(reviewRequest["理由詳細"])}</p><p><strong>対象日時</strong><br>${e(day(reviewRequest["実勤務日"]))} ${e(t(reviewRequest["申請開始"]))}–${e(t(reviewRequest["申請終了"]))}</p>`;$("reviewReason").value="";$("reviewDialog").showModal()}
$("reviewDialog").addEventListener("close",async()=>{const decision=$("reviewDialog").returnValue;if(!reviewRequest||!["approve","reject"].includes(decision))return;const reason=$("reviewReason").value.trim();if(decision==="reject"&&!reason)return message("却下理由を入力してください。",true);const expectedRequestVersion=Number(reviewRequest.request_version);if(!Number.isInteger(expectedRequestVersion)||expectedRequestVersion<1)return message("申請の版情報を確認できません。画面を更新してください。",true);try{await attendanceRequest("reviewRequest",{requestId:reviewRequest.request_id,expectedRequestVersion,decision:decision==="approve"?"承認":"却下",reason});message("申請を処理しました。");reviewRequest=null;await load()}catch(e){message(e.code?`${e.code}: ${e.message}`:`通信結果を確認できませんでした。再押下せず、画面を更新してください。（${e.message}）`,true)}});
function card(label,value){return`<article><small>${label}</small><strong>${value}</strong></article>`}function message(v,err=false){$("message").textContent=v;$("message").classList.toggle("error",err)}function t(v){if(!v)return"—";const d=new Date(v);return Number.isNaN(d.getTime())?String(v).slice(-5):new Intl.DateTimeFormat("ja-JP",{hour:"2-digit",minute:"2-digit",hour12:false,timeZone:"Asia/Tokyo"}).format(d)}function day(v){if(!v)return"—";const d=new Date(v);return Number.isNaN(d.getTime())?String(v):new Intl.DateTimeFormat("ja-JP",{year:"numeric",month:"2-digit",day:"2-digit",timeZone:"Asia/Tokyo"}).format(d)}function cls(v){return v==="稼働中"?"running":v==="開始遅延"?"delay":v==="終了済み"?"done":""}function e(v){const d=document.createElement("div");d.textContent=String(v??"");return d.innerHTML}
