const agencyState={agencies:[],stores:[],editing:null};
const $=id=>document.getElementById(id);
document.addEventListener('DOMContentLoaded',async()=>{try{renderOrderCaseHeader('agencies','代理店・配置ルール管理');const permission=await fetchApiJson('getOrderCasePermission');if(!permission.ok||!permission.data?.can_edit)throw new Error('代理店マスターの編集権限がありません。');bindAgencyEvents();await loadAgencyData();}catch(error){setAgencyMessage(error.message,'error')}});
function bindAgencyEvents(){$('searchInput').addEventListener('input',renderAgencies);$('statusFilter').addEventListener('change',renderAgencies);$('newButton').addEventListener('click',()=>openAgencyEditor());$('cancelButton').addEventListener('click',closeAgencyEditor);$('saveButton').addEventListener('click',saveAgency);$('archiveButton').addEventListener('click',toggleAgencyArchive);}
async function loadAgencyData(){const [agencies,stores]=await Promise.all([fetchApiJson('listAgenciesMaster'),fetchApiJson('listStoresMaster')]);if(!agencies.ok)throw new Error(agencies.message||'代理店一覧を取得できませんでした。');if(!stores.ok)throw new Error(stores.message||'店舗一覧を取得できませんでした。');agencyState.agencies=agencies.data||[];agencyState.stores=stores.data||[];renderAgencies();}
function normalizeAgencyText(value){return String(value||'').trim().normalize('NFKC').replace(/\s+/g,'').toLowerCase()}
function agencyStoreCount(id){return agencyState.stores.filter(store=>String(store.agency_id||'')===String(id||'')&&String(store.status||'active')==='active').length}
function isTrue(value){return String(value||'').toUpperCase()==='TRUE'}
function renderAgencies(){const keyword=normalizeAgencyText($('searchInput').value),filter=$('statusFilter').value;const all=agencyState.agencies;$('activeCount').textContent=all.filter(row=>String(row.status||'active')==='active').length;$('provisionalCount').textContent=all.filter(row=>isTrue(row.provisional)).length;$('archivedCount').textContent=all.filter(row=>row.status==='archived').length;$('storeCount').textContent=agencyState.stores.filter(row=>String(row.status||'active')==='active').length;const rows=all.filter(row=>(filter==='all'||String(row.status||'active')===filter)&&(!keyword||normalizeAgencyText([row.agency_name,row.agency_short_name,row.contact_name].join(' ')).includes(keyword)));$('agencyList').innerHTML=rows.map(row=>{const archived=row.status==='archived',storeCount=agencyStoreCount(row.agency_id);return `<article class="master-row ${archived?'is-archived':''}"><div class="master-name"><strong>${escapeHtml(row.agency_name)}</strong><small>${escapeHtml(row.agency_short_name||row.agency_id||'-')}</small></div><div class="master-meta">担当：${escapeHtml(row.contact_name||'未設定')}<br>店舗：${storeCount}件</div><div class="master-rules">${row.preferred_member_ids?'<span class="rule-badge">代理店指名あり</span>':''}${row.ng_member_ids?'<span class="rule-badge is-ng">代理店NGあり</span>':''}</div><span class="status-badge ${archived?'is-archived':isTrue(row.provisional)?'is-provisional':''}">${archived?'アーカイブ':isTrue(row.provisional)?'仮登録':'有効'}</span><button type="button" data-agency-id="${escapeHtml(row.agency_id)}">編集</button></article>`}).join('')||'<div class="empty">該当する代理店はありません。</div>';$('agencyList').querySelectorAll('[data-agency-id]').forEach(button=>button.addEventListener('click',()=>openAgencyEditor(button.dataset.agencyId)));}
function setAgencyField(id,value){$(id).value=value||''}
function openAgencyEditor(id){const row=id?agencyState.agencies.find(item=>String(item.agency_id)===String(id)):null;agencyState.editing=row||null;setAgencyField('editAgencyId',row?.agency_id);setAgencyField('editAgencyName',row?.agency_name);setAgencyField('editAgencyShortName',row?.agency_short_name);setAgencyField('editContactName',row?.contact_name);setAgencyField('editPhone',row?.phone);setAgencyField('editEmail',row?.email);setAgencyField('editStatus',row?.status||'active');setAgencyField('editPreferredMemberIds',row?.preferred_member_ids);setAgencyField('editPreferredNote',row?.preferred_note);setAgencyField('editNgMemberIds',row?.ng_member_ids);setAgencyField('editNgNote',row?.ng_note);setAgencyField('editMemo',row?.memo);$('editorTitle').textContent=row?`代理店編集：${row.agency_name}`:'代理店を新規登録';$('archiveButton').classList.toggle('hidden',!row);$('archiveButton').textContent=row?.status==='archived'?'復元':'アーカイブ';$('editorBackdrop').classList.remove('hidden');}
function closeAgencyEditor(){$('editorBackdrop').classList.add('hidden');agencyState.editing=null}
function buildAgencyPayload(){return{agency_id:$('editAgencyId').value.trim(),agency_name:$('editAgencyName').value.trim(),agency_short_name:$('editAgencyShortName').value.trim(),contact_name:$('editContactName').value.trim(),phone:$('editPhone').value.trim(),email:$('editEmail').value.trim(),status:$('editStatus').value,preferred_member_ids:$('editPreferredMemberIds').value.trim(),preferred_note:$('editPreferredNote').value.trim(),ng_member_ids:$('editNgMemberIds').value.trim(),ng_note:$('editNgNote').value.trim(),memo:$('editMemo').value.trim(),provisional:'FALSE'}}
async function saveAgency(){const payload=buildAgencyPayload();if(!payload.agency_name){setAgencyMessage('代理店名は必須です。','error');return}$('saveButton').disabled=true;try{const action=payload.agency_id?'updateAgencyMaster':'createAgencyMaster';const result=await postOrderCaseAction(action,payload);if(!result.ok)throw new Error(result.message||'保存できませんでした。');setAgencyMessage(`${payload.agency_name}を保存しました。`,'success');closeAgencyEditor();await loadAgencyData();}catch(error){setAgencyMessage(error.message,'error')}finally{$('saveButton').disabled=false}}
async function toggleAgencyArchive(){if(!agencyState.editing)return;const restoring=agencyState.editing.status==='archived',action=restoring?'復元':'アーカイブ';if(!confirm(`${agencyState.editing.agency_name}を${action}しますか？\n有効な店舗が残る代理店はアーカイブできません。`))return;$('editStatus').value=restoring?'active':'archived';await saveAgency();}
function setAgencyMessage(text,type){$('messageBox').textContent=text||'';$('messageBox').className=`message ${type||''}`}
