/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.router.jsonc --include-runtime=false --strict-vars=false --env-interface=RouterEnv src/router-env.d.ts` (hash: 2538beeb5de42f86ddb6c5ee924035f6)
interface __BaseEnv_RouterEnv {
	ACTIVE_SLOT: string;
	BLUE: Fetcher /* another-portal-slot-blue */;
	GREEN: Fetcher /* another-portal-slot-green */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./router");
	}
	interface Env extends __BaseEnv_RouterEnv {}
}
interface RouterEnv extends __BaseEnv_RouterEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ACTIVE_SLOT">> {}
}
