/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.slot.jsonc --include-runtime=false --strict-vars=false --env-interface=SlotEnv src/slot-env.d.ts` (hash: 6ab998b2a08bdd291c5d6c80d6298b58)
interface __BaseEnv_SlotEnv {
	ASSETS: Fetcher;
	PORTAL_SLOT: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./slot");
	}
	interface BlueEnv {
		ASSETS: Fetcher;
		PORTAL_SLOT: string;
	}
	interface GreenEnv {
		ASSETS: Fetcher;
		PORTAL_SLOT: string;
	}
	interface Env extends __BaseEnv_SlotEnv {}
}
interface SlotEnv extends __BaseEnv_SlotEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PORTAL_SLOT">> {}
}
